### ISSUE TITLE
[v3.23.370a] Error on Startup

### ISSUE THREAD

**Issue by muhuk** [Frege/eclipse-plugin#18]
Looks like Java1.8 is required by impulse.

There are 2 errors in the error log:

        FrameworkEvent ERROR

        org.osgi.framework.BundleException: Could not resolve module: frege.ide [1815]
        Unresolved requirement: Require-Bundle: impulse; bundle-version="0.1.0"
            -> Bundle-SymbolicName: impulse; bundle-version="0.1.0.201510181252"; singleton:="true"
            impulse [1816]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

                at org.eclipse.osgi.container.Module.start(Module.java:434)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
                at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
                at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

        eclipse.buildId=4.5.1.M20150904-0015
        java.version=1.7.0_85
        java.vendor=Oracle Corporation
        BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_SG
        Framework arguments:  -product org.eclipse.epp.package.java.product
        Command-line arguments:  -data file:/home/muhuk/Documents/workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

and:

        FrameworkEvent ERROR

        org.osgi.framework.BundleException: Could not resolve module: impulse [1816]
        Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

                at org.eclipse.osgi.container.Module.start(Module.java:434)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
                at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
                at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
                at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

        eclipse.buildId=4.5.1.M20150904-0015
        java.version=1.7.0_85
        java.vendor=Oracle Corporation
        BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_SG
        Framework arguments:  -product org.eclipse.epp.package.java.product
        Command-line arguments:  -data file:/home/muhuk/Documents/workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

Frege plugin:

        $ ls -l1 frege.ide_3.23.370.a
        total 24
        drwxr-xr-x 3 muhuk muhuk 4096 Oct 19 12:52 frege
        drwxr-xr-x 2 muhuk muhuk 4096 Oct 19 12:52 icons
        drwxr-xr-x 2 muhuk muhuk 4096 Oct 19 12:52 lib
        drwxr-xr-x 2 muhuk muhuk 4096 Oct 19 12:52 META-INF
        -rw-r--r-- 1 muhuk muhuk 4508 Oct 18 12:52 plugin.xml

Impulse:

        $ ls -l1 impulse_0.1.0.201510181252.jar 
        -rw-r--r-- 1 muhuk muhuk 740923 Oct 19 12:52 impulse_0.1.0.201510181252.jar

**Comment by Ingo60** [comment]
Yes, looks like this is the case.

Though I have no idea how this can be, as I compiled frege.ide code and the impulse code in the same Eclipse instance ... I guess there is some "bundle" property or something that causes this.

I hope you can do with java8 meanwhile, as I can look into it not before friday.

**Comment by muhuk** [comment]
No problem. I'll just wait.

**Comment by Ingo60** [comment]
Atamart, you're the thoughest QA I ever experienced. But thank you for that, I need it, apparently.

**Comment by Ingo60** [comment]
Should be fixed now. Please use 3.23.370.b

**Comment by muhuk** [comment]
Thanks Ingo! It seems to have solved the "module named Value" issue too.

But now I'm getting another error from code that used to compile. Filed a separate report: Frege/frege#194

Closing this...
